import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a2d800",
        "surface-container": "#1f1f1f",
        "on-tertiary-fixed-variant": "#454747",
        "primary-container": "#b9f600",
        surface: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#384e00",
        "error-container": "#93000a",
        "on-secondary-container": "#ffd2cc",
        "primary-fixed": "#b9f600",
        primary: "#ffffff",
        "surface-container-highest": "#353535",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#c5020b",
        "on-primary-container": "#516e00",
        "surface-tint": "#a2d800",
        "on-primary": "#263500",
        "inverse-primary": "#4c6700",
        "inverse-on-surface": "#303030",
        secondary: "#ffb4aa",
        "on-background": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "surface-bright": "#393939",
        "tertiary-container": "#e2e2e2",
        tertiary: "#ffffff",
        "on-surface-variant": "#c3caac",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary-fixed": "#ffdad5",
        "secondary-fixed-dim": "#ffb4aa",
        "outline-variant": "#434933",
        "on-primary-fixed": "#141f00",
        "on-tertiary-container": "#636565",
        outline: "#8d9479",
        error: "#ffb4ab",
        "on-secondary": "#690003",
        "tertiary-fixed": "#e2e2e2",
        "on-surface": "#e2e2e2",
        "on-secondary-fixed-variant": "#930005",
        "on-tertiary": "#2f3131",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "on-secondary-fixed": "#410001",
        background: "#131313",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-variant": "#353535",
        "surface-container-low": "#1b1b1b",
        "acid-green": "#a2d800",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "border-width-heavy": "4px",
        "border-width": "2px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        unit: "4px",
      },
      borderWidth: {
        "border-width": "2px",
        "border-width-heavy": "4px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "score-display": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "display-xl": ["var(--font-inter)", "Inter", "sans-serif"],
        "code-sm": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-bold": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "score-display": ["64px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-xl": ["80px", { lineHeight: "72px", letterSpacing: "-0.05em", fontWeight: "900" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "30px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-bold": ["14px", { lineHeight: "16px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
