/* eslint-disable */
/**
 * Generated API contracts.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as roasts from "../roasts.js";

/**
 * A utility for referencing Convex functions in your app's queries and mutations.
 */
declare const fullApi: ApiFromModules<{
  roasts: typeof roasts;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "query" | "mutation">
>;
