/* eslint-disable */
/**
 * Generated API contracts.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { anyApi } from "convex/server";

export const api = anyApi;
